### PR TITLE
ci: Log dynamic library dependencies

### PR DESCRIPTION
**Pull request by joeyparrish**
This should help in debugging non-portable binaries.

### CODE REVIEW

**Comment by mariocynicys** [comment]
Couldn't we use `tee` to not run the commands twice?

**Comment by joeyparrish** [comment]
True.  I could tee to a file to capture it.  I could also capture the output into a variable and echo it back later.

**Comment by joeyparrish** [comment]
Done.  Thanks for the feedback!

**Review by mariocynicys — APPROVED** [review]
I meant that we tee to the stdout and route a copy to the pipe but looks like this is not a thing :laughing:

LGTM

**Pull request merged**
